# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_ui.ui'
#
# Created: Fri Apr 01 21:42:03 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(500, 350)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 40, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lcdNumber_temp = QtGui.QLCDNumber(Form)
        self.lcdNumber_temp.setGeometry(QtCore.QRect(10, 60, 181, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_temp.setFont(font)
        self.lcdNumber_temp.setFrameShape(QtGui.QFrame.Panel)
        self.lcdNumber_temp.setLineWidth(1)
        self.lcdNumber_temp.setNumDigits(7)
        self.lcdNumber_temp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_temp.setProperty("value", 0.0)
        self.lcdNumber_temp.setObjectName(_fromUtf8("lcdNumber_temp"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(210, 40, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lcdNumber_hum = QtGui.QLCDNumber(Form)
        self.lcdNumber_hum.setGeometry(QtCore.QRect(210, 60, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_hum.setFont(font)
        self.lcdNumber_hum.setFrameShape(QtGui.QFrame.Panel)
        self.lcdNumber_hum.setNumDigits(4)
        self.lcdNumber_hum.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_hum.setProperty("value", 0.0)
        self.lcdNumber_hum.setObjectName(_fromUtf8("lcdNumber_hum"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.dateTimeEdit_time = QtGui.QDateTimeEdit(Form)
        self.dateTimeEdit_time.setEnabled(True)
        self.dateTimeEdit_time.setGeometry(QtCore.QRect(150, 10, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dateTimeEdit_time.setFont(font)
        self.dateTimeEdit_time.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dateTimeEdit_time.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.dateTimeEdit_time.setFrame(True)
        self.dateTimeEdit_time.setReadOnly(True)
        self.dateTimeEdit_time.setKeyboardTracking(False)
        self.dateTimeEdit_time.setObjectName(_fromUtf8("dateTimeEdit_time"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 265, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 236, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_cloud_text = QtGui.QLabel(Form)
        self.label_cloud_text.setGeometry(QtCore.QRect(130, 235, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_cloud_text.setFont(font)
        self.label_cloud_text.setObjectName(_fromUtf8("label_cloud_text"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(360, 40, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lcdNumber_pres = QtGui.QLCDNumber(Form)
        self.lcdNumber_pres.setGeometry(QtCore.QRect(330, 60, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber_pres.setFont(font)
        self.lcdNumber_pres.setFrameShape(QtGui.QFrame.Panel)
        self.lcdNumber_pres.setNumDigits(5)
        self.lcdNumber_pres.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_pres.setProperty("value", 0.0)
        self.lcdNumber_pres.setObjectName(_fromUtf8("lcdNumber_pres"))
        self.label_wind_speed_text = QtGui.QLabel(Form)
        self.label_wind_speed_text.setGeometry(QtCore.QRect(80, 265, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_wind_speed_text.setFont(font)
        self.label_wind_speed_text.setObjectName(_fromUtf8("label_wind_speed_text"))
        self.label_wind_dest_text = QtGui.QLabel(Form)
        self.label_wind_dest_text.setGeometry(QtCore.QRect(150, 266, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_wind_dest_text.setFont(font)
        self.label_wind_dest_text.setObjectName(_fromUtf8("label_wind_dest_text"))
        self.label_weather_descr_text = QtGui.QLabel(Form)
        self.label_weather_descr_text.setGeometry(QtCore.QRect(90, 200, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_weather_descr_text.setFont(font)
        self.label_weather_descr_text.setObjectName(_fromUtf8("label_weather_descr_text"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 320, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_time_date = QtGui.QLabel(Form)
        self.label_time_date.setGeometry(QtCore.QRect(150, 320, 341, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_time_date.setFont(font)
        self.label_time_date.setObjectName(_fromUtf8("label_time_date"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "rpi weather", None))
        self.label.setText(_translate("Form", "Температура", None))
        self.label_2.setText(_translate("Form", "Влажность", None))
        self.label_3.setText(_translate("Form", "Текущее время", None))
        self.label_4.setText(_translate("Form", "Погода:", None))
        self.label_5.setText(_translate("Form", "Ветер:", None))
        self.label_6.setText(_translate("Form", "Облачность:", None))
        self.label_cloud_text.setText(_translate("Form", "clouds text", None))
        self.label_9.setText(_translate("Form", "Давление", None))
        self.label_wind_speed_text.setText(_translate("Form", "wind speed", None))
        self.label_wind_dest_text.setText(_translate("Form", "wind direction", None))
        self.label_weather_descr_text.setText(_translate("Form", "weather text", None))
        self.label_7.setText(_translate("Form", "Время данных:", None))
        self.label_time_date.setText(_translate("Form", "data time", None))

